= Hardware specifications

3.1 Where did your run your tests? A laptop, or goldengate?
laptop

3.2 What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)
8 cpus @ 1.30GHz, 32gb of RAM



= Allocations

In `simple.c`, where does the increase in 1040 bytes come from?
Why is the value 1040 bytes?
I got x1018 or 4120 bytes. 4104 from the print statement, and 16 from malloc chunck struct.
By taking out the print statement in between the sbrk calls, you get 0 bytes difference.

How many bytes does `mylloc_list.c` allocate when the program ends? Explain why
this amount makes sense.
4244 bites or 124 more than before. 100 for malloc, and 16 more for a chunk (now 2 chunks)
This makes sense because alloc changes the heap.



= Fragementation

5.1
Fragementation is when there are used and free memory blocks mixed in with eachother.
(There are some free, some used, some more free, etc.) Internal fragmentation is
when this happens within a block when chunk.inUse < chunk.size. External Fragementation
when the avalible memory is split up into section between blocks.

5.2
The initial top of the heap is 0x7f7a9e410000.
Total blocks: 203 Free: 103 Used: 100
Internal unused: total: 158364 average: 1583 smallest: 817 largest: 3967
External unused: total: 144345 average: 1401 smallest: 10 largest: 3984
0
The current top of the heap is 0x7f7a9e467637.
Increased by 349 (0x15d) Kbyte
Total blocks: 213 Free: 113 Used: 100
Internal unused: total: 144377 average: 1443 smallest: 975 largest: 3983
External unused: total: 177549 average: 1571 smallest: 10 largest: 3984
1
The current top of the heap is 0x7f7a9e46d467.
Increased by 373 (0x175) Kbyte
Total blocks: 217 Free: 117 Used: 100
Internal unused: total: 141562 average: 1415 smallest: 932 largest: 3991
External unused: total: 189341 average: 1618 smallest: 10 largest: 3997
2
The current top of the heap is 0x7f7a9e46f3d2.
Increased by 380 (0x17c) Kbyte
Total blocks: 220 Free: 120 Used: 100
Internal unused: total: 152237 average: 1522 smallest: 817 largest: 4000
External unused: total: 201235 average: 1676 smallest: 10 largest: 3998
3
The current top of the heap is 0x7f7a9e4722f0.
Increased by 392 (0x188) Kbyte
Total blocks: 225 Free: 125 Used: 100
Internal unused: total: 143727 average: 1437 smallest: 1097 largest: 3998
External unused: total: 222205 average: 1777 smallest: 10 largest: 3999
4
The current top of the heap is 0x7f7a9e475215.
Increased by 404 (0x194) Kbyte
Total blocks: 216 Free: 116 Used: 100
Internal unused: total: 179922 average: 1799 smallest: 1097 largest: 3990
External unused: total: 189140 average: 1630 smallest: 10 largest: 3999
5
The current top of the heap is 0x7f7a9e4761cd.
Increased by 408 (0x198) Kbyte
Total blocks: 228 Free: 128 Used: 100
Internal unused: total: 142094 average: 1420 smallest: 1701 largest: 3993
External unused: total: 227231 average: 1775 smallest: 10 largest: 4000
6
The current top of the heap is 0x7f7a9e4761cd.
Increased by 408 (0x198) Kbyte
Total blocks: 225 Free: 125 Used: 100
Internal unused: total: 161202 average: 1612 smallest: 1701 largest: 3989
External unused: total: 219943 average: 1759 smallest: 10 largest: 3999
7
The current top of the heap is 0x7f7a9e477185.
Increased by 412 (0x19c) Kbyte
Total blocks: 218 Free: 118 Used: 100
Internal unused: total: 174113 average: 1741 smallest: 1701 largest: 3986
External unused: total: 193697 average: 1641 smallest: 10 largest: 4000
8
The current top of the heap is 0x7f7a9e47813d.
Increased by 416 (0x1a0) Kbyte
Total blocks: 230 Free: 130 Used: 100
Internal unused: total: 143712 average: 1437 smallest: 1615 largest: 3984
External unused: total: 237661 average: 1828 smallest: 10 largest: 4000
9
The current top of the heap is 0x7f7a9e47813d.
Increased by 416 (0x1a0) Kbyte
